global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'observability_example'
    scrape_interval: 5s
    static_configs:
      - targets: ['observabilityexample:5300']
    metrics_path: '/metrics'